defaults:
  - model_checkpoint
  - model_summary
  - learning_rate_monitor
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: 'step_{step:06d}'
  every_n_train_steps: 10000
  save_last: True
  auto_insert_metric_name: False

model_summary:
  max_depth: -1
